### ISSUE TITLE
license

### ISSUE THREAD

**Issue by puckey** [pailhead/three-instanced-mesh#1]
Would you consider releasing this with an MIT license?

**Comment by pailhead** [comment]
There might not be a need for since it's shcheduled to make it into r85 with some modifications. But yes I can do that tomorrow :)

**Comment by puckey** [comment]
I just saw your Three.js InstancedMesh branch, it is exactly what I was looking for. I will be using for a project I am working on and will be sure to provide feedback. Thanks!

**Comment by pailhead** [comment]
You can check out this discussion for a bit of history, it more or less started with the state of this module, and ended where the branch is at now. The matrices are no longer being computed on the CPU, although i think this should still happen if it's  known ahead of time that the instances will be static. The way the material is being decorated is a bit clunky, but i tried not to modify anything but the shaders. 

https://github.com/mrdoob/three.js/pull/10750

Latest example:
http://dusanbosnjak.com/test/webGL/three-instanced-mesh/webgl_instanced_mesh_v3.html

**Comment by pailhead** [comment]
@puckey 

Help my noobness learn open source :) 

`MIT` was in the package.json all along, do i need to include the license in the readme? What's considered:

>  releasing this with an MIT license?

**Comment by puckey** [comment]
Yeah normally you would also include a 'LICENSE' file in the root of the repo. Three.js does this too (also MIT): https://github.com/mrdoob/three.js/blob/dev/LICENSE

**Comment by pailhead** [comment]
Makes sense, thanks!

**Comment by pailhead** [comment]
well i finally did this
