### ISSUE TITLE
Intested in an instance-aware racyast method?

### ISSUE THREAD

**Issue by wmurphyrd** [pailhead/three-instanced-mesh#13]
The way that three handles raycasting by having the mesh object provide is own `.raycast` method makes it quite straightforward to extend `InstancedMesh` to support the standard raycaster. I have an implementation adapted from the standard Mesh.racyast method I could prepare in a PR if you're interested. It is, however, incomplete. For my use case I only need to check bounding sphere collisions against each instance, so I have not adapted the code beyond that point which would go further to determine face and point intersection.

**Comment by pailhead** [comment]
Hi, sorry for the late reply. Could this be made as a plugin of some sort? I'm worried that this can have way too many use cases to settle on just one. I actually wasn't aware of the `.raycast` method, maybe this is enough, and some code could be provided as example?

**Comment by Zetaphor** [comment]
@wmurphyrd I would be very much interested in seeing the code for your raycasting solution

**Comment by wmurphyrd** [comment]
@zetaphor sorry I've left that job and no longer have the option to share that code. It was not extremely difficult to modify the three.js core raycaster to loop over the instances. If you attempt it, I'd be happy to answer questions that arise

**Comment by pailhead** [comment]
I'm generally against coupling this with this library in it's current form. I think you can keep a separate structure for your raycasting and other stuff, while using this to just render whatever structure you end up with. The articles mentioned in readme go over this. Otherwise, i'd consider changing this api, into something that has a class representing a single instance in one instanced draw.

**Comment by Zetaphor** [comment]
@wmurphyrd I'm making an attempt to modify the A-Frame raycaster to intersect with the instanced geometries. I've completely removed the filter on my raycaster and am looking at the rawIntersections coming back. It appears that without any geometry the raycaster is never intersecting with the instanced objects. Where else should I be looking?
