### ISSUE TITLE
Is needsUpdate method redundant?

### ISSUE THREAD

**Issue by trusktr** [pailhead/three-instanced-mesh#26]
Isn't it implied that the object needs an update if we modify position, rotation, etc? The need to call `needsUpdate` seems redundant.

With Three.js `Mesh`, we just set a `rotation` or `position` and we're done. With `InstancedMesh`, if we call something like `setPositionAt` then that implies it needs an update.

Is there a situation when we don't want to call it? Seems like it would be more natural to follow the same pattern as with `Mesh` (we don't need to tell it that update is needed).

**Comment by pailhead** [comment]
I'd say not necessarily, i'd be in favor of an `autoUpdate` flag or something like `Scene` has. Maybe you want to update something over several frames updating the buffer only once. Although:
>With Three.js Mesh...

It could be autoupdating if the whole scene graph is set to autoupdate. 

I'm not sure what to do with this package now that three has it's own instanced mesh.

**Comment by trusktr** [comment]
> I'm not sure what to do with this package now that three has it's own instanced mesh.

Maybe this? https://github.com/pailhead/three-instanced-mesh/issues/17#issuecomment-555300368 😃 

The idea being to make the workflow just like working with any other regular Meshes in the tree. Easier for the user.
