### ISSUE TITLE
setPositionAt(), setQuaternionAt(), setScaleAt() should set the needsUpdate flag to true.

### ISSUE THREAD

**Issue by PERECil** [pailhead/three-instanced-mesh#3]
When dynamically setting the position / quaternion / scale after the object has been added to the scene, setting new values for the attributes doesn't automatically triggers the needsUpdate flag, and the end user have to set it manually.

This should be done automatically.

Bonus task: only set the flag if the value has really changed.

**Comment by pailhead** [comment]
Oops i think i butt-dialed this :D 

Agreed, will address this.

**Comment by pailhead** [comment]
Upon revisiting, I'm not so sure about this one. I think that with three you need to set the needsUpdate manually as well, so maybe best to keep it aligned with that.
