### ISSUE TITLE
No setRotationAt?

### ISSUE THREAD

**Issue by mokargas** [pailhead/three-instanced-mesh#4]
Hey @pailhead, 

Great stuff (I have this working in aframe.io VR), but how would I give cluster items a random rotation distribution? I figured setRotationAt would be a logical call, but seems it isn't implemented.

**Comment by pailhead** [comment]
@mokargas 

I've found some time to take another pass at this. The quaternion ended up being a faster solution if i recall, but i don't really remember. I'll dig into it, there was a lot of input from three, when i thought this might make it in, so maybe it's time to just ignore all that and start fresh :)

In the meanwhile, why doesn't `setQuaternionAt()` work for you?

**Comment by pailhead** [comment]
For the time being I think that `setQuaternionAt()` makes sense, and that obtaining a quaternion should be handled outside of this scope.
