### ISSUE TITLE
THREE.InstancedBufferAttribute: The constructor now expects normalized as the third argument.

### ISSUE THREAD

**Issue by SolalDR** [pailhead/three-instanced-mesh#8]
THREE.js throw an error when using THREE.InstancedMesh, you should replace
``` javascript
new THREE.InstancedBufferAttribute( new Float32Array( this.numInstances * 3 ) , 3 , 1 ) 
```
with something like this
``` javascript
new THREE.InstancedBufferAttribute( new Float32Array( this.numInstances * 3 ) , 3 , false )
```

**Comment by pailhead** [comment]
Thanks for reporting this. Would you happen to know when this was added? Was it the most recent version? I'm not entirely sure how to bump the versioning to correspond with what happens in three.js

**Comment by pailhead** [comment]
Mkay so, i think i fixed this and bumped the version to 0.96.0 since this is where the signature was changed.  Now this wont work with pre 96, but i'm hoping this makes sense and people can still use the previous version.

**Comment by pailhead** [comment]
I tried to use both signatures depending on the version of three passed. Looks clunky but seems to be working, any thoughts? @SolalDR 

https://github.com/pailhead/three-instanced-mesh/blob/master/index.js#L377

**Comment by SolalDR** [comment]
I don't think this is necessary. If people want to use a previous version of three they should use a previous version of  three-instanced-mesh as well. 

Maybe just throw a warning after checking the signature ?

**Comment by pailhead** [comment]
I don't know how to version this, i think i started with whatever version of three was available at the time, and i didn't test for anything before. R96 broke this interface, so yeah having a 0.96.0 with a different one would make sense. But then what about an improvement that has nothing to do with the interface which version should that be? 0.96.1 and 0.88.1? abandon the old one?

**Comment by SolalDR** [comment]
If your improvement has nothing to do with three, I think you should increment version like "0.96.1" and change the release only when a break compatibility occure.
