### ISSUE TITLE
[discussion] Usage with custom shaders

### ISSUE THREAD

**Issue by hugohil** [pailhead/three-instanced-mesh#9]
Hey,

Actually it is not an issue, but took me some time to achieve this and I wanted to share the way I did it so we can discuss it and people looking at this can have an idea.

So I wanted to use a custom fragment shader, and have somewhat of a control over which instance I'm computing for (i.e I use noise and I want my noise to be seed individually for each instance).

What I did is that I added an attribute to my instanced geometry that is simply the index of the instance:

```js
// count = the number of instances I have

const indexes = new Float32Array([...Array(count).keys()])
const indexesAttribute = new THREE.InstancedBufferAttribute(indexes, 1)
myInstancedMesh.geometry.addAttribute('instanceIndex', indexesAttribute)
```

So from that point, I can access a `attribute float instanceIndex;` in my vertex shader, and pass it to some `varying` for the fragment.

Then I took `THREE.ShaderChunk.meshbasic_vert`, copied it and added the varying stuffs. So now it looks ike:

```glsl
#include <common>
#include <uv_pars_vertex>
#include <uv2_pars_vertex>
#include <envmap_pars_vertex>
#include <color_pars_vertex>
#include <fog_pars_vertex>
#include <morphtarget_pars_vertex>
#include <skinning_pars_vertex>
#include <logdepthbuf_pars_vertex>
#include <clipping_planes_pars_vertex>

attribute float instanceIndex;
varying float vIndex;

void main() {
  vIndex = instanceIndex;

  #include <uv_vertex>
  #include <uv2_vertex>
  #include <color_vertex>
  #include <skinbase_vertex>
  #ifdef USE_ENVMAP
  #include <beginnormal_vertex>
  #include <morphnormal_vertex>
  #include <skinnormal_vertex>
  #include <defaultnormal_vertex>
  #endif
  #include <begin_vertex>
  #include <morphtarget_vertex>
  #include <skinning_vertex>
  #include <project_vertex>
  #include <logdepthbuf_vertex>
  #include <worldpos_vertex>
  #include <clipping_planes_vertex>
  #include <envmap_vertex>
  #include <fog_vertex>
}
```

And the fragment can be any custom fragment shader, and it can access which instance it's on via `varying float vIndex;`.

It's a bit hacky, but it does what I needed.

Maybe the `instanceIndex` attribute could be assigned with some flag when creating the instanced mesh ?

Also, I thinkg it's related to #2

**Comment by pailhead** [comment]
Hi.

The GLSL present in this module is the minimum tweaking that's needed to make `mesh.position` be instanced. Ie. it should apply only to the "built in" materials. 

I think that this is a different responsibility. 

If you end up writing any GLSL you're no longer using the built in materials, or you are extending them, in either case you would still use these (patched) chunks just like if you were doing something else. Ie. `varying float vIndex` is not useful without a fragment shader. What you've done there seems like a valid way to use the GLSL from this module. Where what lives in which chunk could perhaps be refactored depending on the needs.

Take a look at these:

https://github.com/pailhead/three-refactor-chunk-material
https://medium.com/@pailhead011/extending-three-js-materials-with-glsl-78ea7bbb9270
